# config/services.yaml
parameters:
    app.mailer_from: '%env(default:APP_MAILER_FROM_DEFAULT:MAILER_FROM)%'
    APP_MAILER_FROM_DEFAULT: 'no-reply@example.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Command/FixturesDryRunCommand.php'

    App\Security\AuthLinkService:
        arguments:
            $mailFrom: '%app.mailer_from%'
